const MAX_DERIVATION_PATH_DEPTH_TO_CHECK_PRIVATE_KEY = 6;

export { MAX_DERIVATION_PATH_DEPTH_TO_CHECK_PRIVATE_KEY };

export {
  DEFAULT_ADA_INSTANCE_PARAMETERS,
  DEFAULT_AVAX_INSTANCE_PARAMETERS,
  DEFAULT_BTC_INSTANCE_PARAMETERS,
  DEFAULT_TRX_INSTANCE_PARAMETERS,
  DEFAULT_TON_INSTANCE_PARAMETERS,
  DEFAULT_SUI_INSTANCE_PARAMETERS,
  DEFAULT_BCH_INSTANCE_PARAMETERS,
  DEFAULT_XRP_INSTANCE_PARAMETERS,
  DEFAULT_BNB_INSTANCE_PARAMETERS,
  DEFAULT_EVM_INSTANCE_PARAMETERS,
  DEFAULT_DOT_INSTANCE_PARAMETERS,
  DEFAULT_SOL_INSTANCE_PARAMETERS,
  DEFAULT_DOGE_INSTANCE_PARAMETERS,
  DEFAULT_ZEC_INSTANCE_PARAMETERS,
  DEFAULT_APT_INSTANCE_PARAMETERS,
} from "./default-instance-parameters.constant.js";
export {
  INDEX_LOOKUP_FROM,
  INDEX_LOOKUP_TO,
  FIRST_ITEM_INDEX,
  MNEMONIC,
} from "./__tests__/index.js";
