type DerivationTypeMap = {
  avaxX: "avaxX";
  avaxP: "avaxP";
  btcLegacy: "btcLegacy";
  btcSegWit: "btcSegWit";
  btcP2wshInP2sh: "btcP2wshInP2sh";
  btcP2wsh: "btcP2wsh";
  btcNativeSegWit: "btcNativeSegWit";
  btcTaproot: "btcTaproot";
  bchLegacy: "bchLegacy";
  bchCashAddr: "bchCashAddr";
  adaBase: "adaBase";
  adaReward: "adaReward";
  adaEnterprise: "adaEnterprise";
  bnbBase: "bnbBase";
  evmBase: "evmBase";
  xrpBase: "xrpBase";
  xrpX: "xrpX";
  trxBase: "trxBase";
  tonBase: "tonBase";
  suiBase: "suiBase";
  dotBase: "dotBase";
  solBase: "solBase";
  dogeLegacy: "dogeLegacy";
  zecTransparent: "zecTransparent";
  aptBase: "aptBase";
  aptLegacy: "aptLegacy";
};

export { type DerivationTypeMap };
