const HARDENED_RANGE_OFFSET = 2147483648; // 2 ** 31;

const DECIMAL_SYSTEM_IDENTIFIER = 10;

const HEX_PREFIX = "0x";

const MINIMUM_MULTISIG_ADDRESS_SIGNATURES_AMOUNT = 1;

const SECP256K1_COMPRESSED_PUBLIC_KEY_LENGTH = 33;

export {
  HARDENED_RANGE_OFFSET,
  DECIMAL_SYSTEM_IDENTIFIER,
  HEX_PREFIX,
  MINIMUM_MULTISIG_ADDRESS_SIGNATURES_AMOUNT,
  SECP256K1_COMPRESSED_PUBLIC_KEY_LENGTH,
};
