const DERIVATION_PATH_DELIMITER = "/";

const HARDEN_RANGE_START_INDEX = 2147483648; // 2 ** 31;

const HARDENED_SUFFIX = "'";

const MASTER_KEY_SYMBOL = "m";

const DECIMAL_SYSTEM_IDENTIFIER = 10;

export {
  DERIVATION_PATH_DELIMITER,
  HARDEN_RANGE_START_INDEX,
  HARDENED_SUFFIX,
  MASTER_KEY_SYMBOL,
  DECIMAL_SYSTEM_IDENTIFIER,
};
