const HARDEN_RANGE_START_INDEX = 2147483648; // 2 ** 31;

const DECIMAL_SYSTEM_IDENTIFIER = 10;

const HEX_PREFIX = "0x";

const MINIMUM_MULTISIG_ADDRESS_SIGNATURES_AMOUNT = 1;

export {
  HARDEN_RANGE_START_INDEX,
  DECIMAL_SYSTEM_IDENTIFIER,
  HEX_PREFIX,
  MINIMUM_MULTISIG_ADDRESS_SIGNATURES_AMOUNT,
};
