const VALIDATION_MESSAGE_TO_SIGN = "validation message";
const APTOS_LIBRARY_PRIVATE_KEY_DELIMITER = "-";
const APTOS_LIBRARY_PRIVATE_KEY_DELIMITER_LENGTH = 1;

export {
  VALIDATION_MESSAGE_TO_SIGN,
  APTOS_LIBRARY_PRIVATE_KEY_DELIMITER,
  APTOS_LIBRARY_PRIVATE_KEY_DELIMITER_LENGTH,
};
