const MAX_DERIVATION_PATH_DEPTH_TO_CHECK_PRIVATE_KEY = 6;

export { MAX_DERIVATION_PATH_DEPTH_TO_CHECK_PRIVATE_KEY };
export { INDEX_LOOKUP_FROM, INDEX_LOOKUP_TO, FIRST_ITEM_INDEX } from "./__tests__/index.js";
