const FIRST_ADDRESS_INDEX = 0;

const EMPTY_MNEMONIC = "";

const SEARCH_FROM_MNEMONIC_LIMIT = 20;

const DERIVATION_PATH_DELIMITER = "/";

export {
  FIRST_ADDRESS_INDEX,
  EMPTY_MNEMONIC,
  SEARCH_FROM_MNEMONIC_LIMIT,
  DERIVATION_PATH_DELIMITER,
};
