export {
  getNetwork,
  DEFAULT_ADA_INSTANCE_PARAMETERS,
  DEFAULT_AVAX_INSTANCE_PARAMETERS,
  DEFAULT_BTC_INSTANCE_PARAMETERS,
  DEFAULT_TON_INSTANCE_PARAMETERS,
  DEFAULT_TRX_INSTANCE_PARAMETERS,
  DEFAULT_SUI_INSTANCE_PARAMETERS,
  DEFAULT_BCH_INSTANCE_PARAMETERS,
  DEFAULT_XRP_INSTANCE_PARAMETERS,
  DEFAULT_BNB_INSTANCE_PARAMETERS,
} from "@/modules/network/index.js";
