type DerivationTypeMap = {
  avaxX: "avaxX";
  avaxP: "avaxP";
  legacy: "legacy";
  segWit: "segWit";
  p2wshInP2sh: "p2wshInP2sh";
  p2wsh: "p2wsh";
  nativeSegWit: "nativeSegWit";
  taproot: "taproot";
  cashAddr: "cashAddr";
  adaBase: "adaBase";
  reward: "reward";
  enterprise: "enterprise";
  bnb: "bnb";
  evm: "evm";
  transparent: "transparent";
  sol: "sol";
  xrpBase: "xrpBase";
  xrpX: "xrpX";
  trxBase: "trxBase";
  tonV1r1: "tonV1r1";
  tonV1r2: "tonV1r2";
  tonV1r3: "tonV1r3";
  tonV2r1: "tonV2r1";
  tonV2r2: "tonV2r2";
  tonV3r1: "tonV3r1";
  tonV3r2: "tonV3r2";
  tonV4r1: "tonV4r1";
  tonV5r1: "tonV5r1";
};

export { type DerivationTypeMap };
